M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date pon, 2 paź 2023, 16:43:59
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-02T16:43:59+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.6355Y-1.0716
X3.8324Y-1.0716
T2
X3.7339Y-1.3708
T0
M30
